<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="filter-block">
        <strong role="heading" aria-level="2" class="block-title">
            <?php /* @escapeNotVerified */ echo __('Shop By') ?>
            <button id="filter-toggle-button" class="filter-toggle-button" type="button" aria-expanded="false" aria-controls="filters-content">
                <?php /* @escapeNotVerified */ echo __('Toggle Filters') ?>
            </button>
        </strong>
        <div class="block-content filter-content lof" id="filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>

            <?php $wrapOptions = false; $activeKey = 0; $activeArray = []; ?>
            <?php foreach ($block->getFilters() as $key => $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content">
                    <?php  $wrapOptions = true; endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter); ?></div>
                    </div>
                    <?php
                        if ($block->getRequest()->getParam($filter->getRequestVar())) {
                            $activeArray[] = $activeKey;
                        }
                        $activeKey++;
                    ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
                <script type="text/x-magento-init">
                    {
                        "#narrow-by-list": {
                            "accordion": {
                                "openedState": "active",
                                "collapsible": true,
                                "active": <?= sizeof($activeArray) ? $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($activeArray) : 'false' ?>,
                                "multipleCollapsible": true
                            },
                            "Lof_LayeredNavigation/js/layer": {}
                        }
                    }
                </script>
            <?php endif; ?>
            <div id="lof_overlay" class="lof_overlay">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>" alt="Loading...">
            </div>
        </div>
    </div>
<?php endif; ?>
